name: "GLAMOS IndoorMapping"
description: "My first real add-on!"
version: "1.0.10"
slug: "glamos_indoormapping"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ingress: true
#stage: stable, experimental or deprecated
#advanced: Set this to true to require the user to have enabled "Advanced" mode for it to show. -> AKO stage NIJE stable
#OPCIJE ZA POSTAVLJANJE ADD-ON U LIJEVI PANEL
# panel_icon
# panel_title
# panel_admin
#OPIS MOGUCNOSTI ADD-ONA
#services:
#ingress OPCIJE?
