name: "GLAMOS IndoorMapping"
version: "1.0.13"
slug: "glamos_indoormapping"
description: "Create building floor plans and visualize them in 3D"
url: "https://glamos.eu/walkapp/"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
startup: services
ingress: true
privileged:
  - BPF
  - DAC_READ_SEARCH
  - IPC_LOCK
  - NET_ADMIN
  - NET_RAW
  - PERFMON
  - SYS_ADMIN
  - SYS_MODULE
  - SYS_NICE
  - SYS_PTRACE
  - SYS_RAWIO
  - SYS_RESOURCE
  - SYS_TIME
full_access: true
# options:
#   ha_port: 7123
# schema:
#   ha_port: int
#stage: stable, experimental or deprecated
#advanced: Set this to true to require the user to have enabled "Advanced" mode for it to show. -> AKO stage NIJE stable
#OPCIJE ZA POSTAVLJANJE ADD-ON U LIJEVI PANEL
# panel_icon
# panel_title
# panel_admin
#UKOLIKO ZELIMO DOHVACAT IMAGE CONTAINERA SA DOCKER HUB ILI GITUHB PACKAGES
#image: ghcr.io/mincka/firefox-{arch} # If you use this option, set the active docker tag using the version option
